CREATE TABLE CLIENTE(
	PKCPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(20)
);

CREATE TABLE TELEFONE(
    PKTELEFONE INTEGER PRIMARY KEY,
	CPF VARCHAR(15),
	TELEFONE VARCHAR(15) NOT NULL,
	FOREIGN KEY(CPF) REFERENCES CLIENTE(PKCPF)
);

CREATE TABLE ENDERECO(
    PKENDERECO INTEGER PRIMARY KEY,
	CPF VARCHAR(15),
	RUA_NUMERO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30)NOT NULL,
	MUNICIPIO VARCHAR(30) NOT NULL,
	ESTADO CHAR(2),
	CEP VARCHAR(10),
	FOREIGN KEY(CPF) REFERENCES CLIENTE(PKCPF)
);

CREATE TABLE LOJA(
    PKLOJA INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(50)
);

CREATE TABLE PRODUTO(
    PKPRODUTO INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(50)NOT NULL,
	QTD_ESTOQUE INTEGER NOT NULL,
	UNIDADE_ARMAZENADA VARCHAR(20),
	FKLOJA INTEGER,
	VALOR_UNIDADE DECIMAL(10,2),
	FOREIGN KEY(FKLOJA)REFERENCES LOJA(PKLOJA)
);

CREATE TABLE VENDEDOR(
    PKCPF VARCHAR(15)PRIMARY KEY,
	NOME VARCHAR(50),
	FKLOJA INTEGER,
	FOREIGN KEY(FKLOJA)REFERENCES LOJA(PKLOJA)
);
	
CREATE TABLE VENDA(
    PKVENDA INTEGER PRIMARY KEY,
	DATA_HORA TIMESTAMP,
	VALOR DECIMAL(10,2),
	FKCLIENTE VARCHAR(15),
	FOREIGN KEY(FKCLIENTE)REFERENCES CLIENTE(PKCPF),
    FOREIGN KEY(FKLOJA) REFERENCES LOJA(PKLOJA),
	FOREIGN KEY(FKVENDEDOR)REFERENCES VENDEDOR(PKCPF)
);
	
CREATE TABLE VENDA_PRODUTO(
    FKVENDA INTEGER,
	FKPRODUTO INTEGER,
	QUANTIDADE INTEGER,
	PRIMARY KEY(FKVENDA,FKPRODUTO),
	FOREIGN KEY(FKVENDA) REFERENCES VENDAS(PKVENDA),
	FOREIGN KEY(FKPRODUTO) REFERENCES PRODUTO(PKPRODUTO)
);